spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yumoto?characterEncoding=utf-8&useSSL=false
    username: root
    password: Lyh20031210
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
