server:
  port: 9999
spring:
  application:
    name: gateway-service
  profiles:
    active: k8s
  cloud:
    gateway:
      discovery:
        locator:
          #开启以服务id去注册中心上获取转发地址
          enabled: true
          ##小写serviceId
#          lower-case-service-id: true
      routes:
        - id: productSearchClient
          uri: lb://productSearchClient
          filters:
            - StripPrefix=1
          predicates:
            - Path=/productSearch/**
        - id: productAddClient
          uri: lb://productAddClient
          filters:
            - StripPrefix=1
          predicates:
            - Path=/productAdd/**
        - id: productSubClient
          uri: lb://productSubClient
          filters:
            - StripPrefix=1
          predicates:
            - Path=/productSub/**
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5         #续约间隔时间
    lease-expiration-duration-in-seconds: 15     #续约到期时间
  client:
    register-with-eureka: true
    fetch-registry: true


